In [1]:
from qutip.operators import qeye
from qutip.qip.gates import rx,ry
from qutip.states import basis
from numpy import pi
import random
from random_single_clifford import random_single_clifford, random_clifford_sequence

<ipython-input-1-1ff0110cb559>:2: DeprecationWarning: Importation from qutip.qip.gates is deprecated.Please use e.g.
 from qutip.qip.operations import cnot

  from qutip.qip.gates import rx,ry


# Single Qubit Clifford Gates

Set of gates is {I,$X_{\frac{\pi}{2}}$,$Y_{\frac{\pi}{2}}$,$X_{\pi}$,$X_{\pi}$}

In [2]:
cliff_gates = [qeye(2),rx(pi/2),ry(pi/2),rx(pi),ry(pi)]

In [3]:
for i in range(2):
    print(random.choice(cliff_gates))

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[0.70710678+0.j         0.        -0.70710678j]
 [0.        -0.70710678j 0.70710678+0.j        ]]


Now within a function

## Create sequence of Clifford gates

Important to note that last gate must be inverse of all other gates. Also need to bear in mind the sequencing of the gates in the list and in which order they are applied.

In [4]:
n_gates = 3

In [5]:
sequence = [None]*n_gates
final = qeye(2)
for i in range(n_gates-1):
    a_random_clifford = random_single_clifford()
    sequence[i] = a_random_clifford
    final = a_random_clifford*final
    
sequence[n_gates-1] = final.inv()

In [6]:
stat_0 = basis(2,0)

for gate in sequence:
    stat_0 = gate*stat_0
    
print(stat_0)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]


Now in a function

In [7]:
sequence = random_clifford_sequence(10)

In [8]:
sequence

[Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
 Qobj data =
 [[ 0.70710678 -0.70710678]
  [ 0.70710678  0.70710678]],
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
 Qobj data =
 [[ 0.70710678 -0.70710678]
  [ 0.70710678  0.70710678]],
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
 Qobj data =
 [[6.123234e-17+0.j 0.000000e+00-1.j]
  [0.000000e+00-1.j 6.123234e-17+0.j]],
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
 Qobj data =
 [[ 6.123234e-17 -1.000000e+00]
  [ 1.000000e+00  6.123234e-17]],
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
 Qobj data =
 [[ 0.70710678 -0.70710678]
  [ 0.70710678  0.70710678]],
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
 Qobj data =
 [[0.70710678+0.j         0.        -0.70710678j]
  [0.        -0.70710678j 0.70710678+0.j        ]],
 Quantum object: dims 